/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioLoginRouteImport } from './routes/studio-login'
import { Route as StudioCreditsRouteImport } from './routes/studio-credits'
import { Route as StudioBridgeRouteImport } from './routes/studio-bridge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AideoRouteImport } from './routes/aideo'
import { Route as IndexRouteImport } from './routes/index'

const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/studio-login',
  path: '/studio-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCreditsRoute = StudioCreditsRouteImport.update({
  id: '/studio-credits',
  path: '/studio-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBridgeRoute = StudioBridgeRouteImport.update({
  id: '/studio-bridge',
  path: '/studio-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AideoRoute = AideoRouteImport.update({
  id: '/aideo',
  path: '/aideo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aideo': typeof AideoRoute
  '/profile': typeof ProfileRoute
  '/studio-bridge': typeof StudioBridgeRoute
  '/studio-credits': typeof StudioCreditsRoute
  '/studio-login': typeof StudioLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aideo': typeof AideoRoute
  '/profile': typeof ProfileRoute
  '/studio-bridge': typeof StudioBridgeRoute
  '/studio-credits': typeof StudioCreditsRoute
  '/studio-login': typeof StudioLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aideo': typeof AideoRoute
  '/profile': typeof ProfileRoute
  '/studio-bridge': typeof StudioBridgeRoute
  '/studio-credits': typeof StudioCreditsRoute
  '/studio-login': typeof StudioLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aideo'
    | '/profile'
    | '/studio-bridge'
    | '/studio-credits'
    | '/studio-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aideo'
    | '/profile'
    | '/studio-bridge'
    | '/studio-credits'
    | '/studio-login'
  id:
    | '__root__'
    | '/'
    | '/aideo'
    | '/profile'
    | '/studio-bridge'
    | '/studio-credits'
    | '/studio-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideoRoute: typeof AideoRoute
  ProfileRoute: typeof ProfileRoute
  StudioBridgeRoute: typeof StudioBridgeRoute
  StudioCreditsRoute: typeof StudioCreditsRoute
  StudioLoginRoute: typeof StudioLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-login': {
      id: '/studio-login'
      path: '/studio-login'
      fullPath: '/studio-login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-credits': {
      id: '/studio-credits'
      path: '/studio-credits'
      fullPath: '/studio-credits'
      preLoaderRoute: typeof StudioCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-bridge': {
      id: '/studio-bridge'
      path: '/studio-bridge'
      fullPath: '/studio-bridge'
      preLoaderRoute: typeof StudioBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aideo': {
      id: '/aideo'
      path: '/aideo'
      fullPath: '/aideo'
      preLoaderRoute: typeof AideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideoRoute: AideoRoute,
  ProfileRoute: ProfileRoute,
  StudioBridgeRoute: StudioBridgeRoute,
  StudioCreditsRoute: StudioCreditsRoute,
  StudioLoginRoute: StudioLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
